### ISSUE TITLE
Issue with Quickbooks General Ledger Running balance Field

### ISSUE THREAD

**Issue by bernhardF1984** [fivetran/dbt_quickbooks#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

DBT creates the General Ledger. In that table tehre is a column called running balance. This is later used for all 3 importnat accounting reports:
Cashflow, Balance sheet aand P&L.
The running balance for the latest date should be equal to the account balance field in the accounts table. As after we take all transactions since the beginning of time we should end up with the correct current balance.
The issue is, for some accounts i see that there is a big discrepancy, there is an issue with the running balance calculation it doesn't end up to the current account balance.
I am using fivetran Quickstart dbt, so i am not running it on my dbt projectm, rathe rit runs on fivetran dbt, with the configuration that fivetran sets.

### Expected behavior

running balance for the lastest date should equal to the current account balance in the account table for that same accountid.

### dbt Project configurations

fivetran configuration, i don't know what they are using

### Package versions

fivetran configuration, i don't know what they are using

### What database are you using dbt with?

bigquery

### dbt Version

fivetran configuration, i don't know what they are using

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @bernhardF1984 thanks for opening this issue and providing the context around the issue you are seeing.

I am happy to jump in and take a look. I do want to confirm real quick that for one of the accounts where you see the big discrepancy, are you able to confirm that the `balance` in the account table matches what you see in the QuickBooks UI? I ask, because we have seen a few cases where the running balance is calculating properly but the value populated by QuickBooks in the account table is not consistent. 

I will continue to investigate on my end if there is something going awry. Additionally as you mentioned this is only the case for some accounts. Do you know if there is a trend in the type of accounts where you see this type of discrepancy?

**Comment by bernhardF1984** [comment]
Hi Joe,

i will try to check reg. QuickBooks UI and i will also try to see if i can
find other accounts with the discrepancy.

**Comment by fivetran-joemarkiewicz** [comment]
This has been addressed in the latest QuickBooks release. As such, I will close out this ticket. Please feel free to reopen if you feel this has not been addressed in the dbt package. Thanks!
