### ISSUE TITLE
[Bug] Duplicated deposit entries in General Ledger transformation

### ISSUE THREAD

**Issue by kelsey-fecho** [fivetran/dbt_quickbooks#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When transforming from the `deposit` and `deposit line` table to the `QUICKBOOKS__GENERAL_LEDGER` table, we see duplication of deposit lines for a subset of accounts. 

### Relevant error log or model output

```shell
Between these two select statements, the deposit lines selected are doubling:
select * from quickbooks.deposit_line dl left join quickbooks.deposit d on dl.deposit_id = d.id

where deposit_account_id in (432, 435);

select  

*

-- case when REGEXP_LIKE(gl.ACCOUNT_NUMBER::numeric, '^[0-9]+$') then floor(gl.ACCOUNT_NUMBER::numeric / 10) * 10
--     else 65700 -- or some default value indicating an error
-- end as INT_ACCOUNT_NUMBER  

from <schema>.QUICKBOOKS_QUICKBOOKS.QUICKBOOKS__GENERAL_LEDGER as gl
where date_trunc('month', transaction_date) = '2024-01-01'
and account_name like '%Deposit%';
```

### Expected behavior

For each transaction id and account number pair, we'd expect to only see one record hitting the general ledger.

### dbt Project configurations

We utilize the Fivetran Quickstart models out of the box.

### Package versions

We utilize the Fivetran Quickstart models out of the box.

### What database are you using dbt with?

snowflake

### dbt Version

We aren't hosting our own, we're using the Fivetran UI.

### Additional Context

[2024-02-15 1_19pm (1).csv](https://github.com/fivetran/dbt_quickbooks/files/14301305/2024-02-15.1_19pm.1.csv)
[2024-02-15 1_19pm.csv](https://github.com/fivetran/dbt_quickbooks/files/14301306/2024-02-15.1_19pm.csv)

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-avinash** [comment]
Hi @kelsey-fecho ! Thanks for bringing this to our attention. 

I'm wondering, might you happen to have has multiple [undeposited funds accounts](https://github.com/fivetran/dbt_quickbooks/blob/eb968fbb09733ef484cd4d80ff850b78e5df5cac/models/double_entry_transactions/int_quickbooks__deposit_double_entry.sql#L27-L37)? In the intermediate model, [we essentially do a cross join](https://github.com/fivetran/dbt_quickbooks/blob/eb968fbb09733ef484cd4d80ff850b78e5df5cac/models/double_entry_transactions/int_quickbooks__deposit_double_entry.sql#L59-L60) on the undeposited fund accounts. If there are multiple accounts that fit [this criteria](https://github.com/fivetran/dbt_quickbooks/blob/eb968fbb09733ef484cd4d80ff850b78e5df5cac/models/double_entry_transactions/int_quickbooks__deposit_double_entry.sql#L34-L36), we could get duplicates originating from this model.

This is also the reason we included the `quickbooks__undeposited_funds_reference` variable to allow folks to adjust this if there were multiple accounts in their environment. But that variable is not configurable in Quickstart so that filter is probably not working as intended for your purpose.

If that's not the case, would you be willing to email the solutions team at solutions@fivetran.com with details about your account? We might need to request data access to look into your `int_quickbooks__deposit_double_entry` model to see what might be causing issues.

**Comment by kelsey-fecho** [comment]
@fivetran-avinash ahh, we do have multiple undeposited fund accounts in that table! That would do the trick. Since it's not we don't have that filter available, are there any other workarounds we could?

**Comment by kelsey-fecho** [comment]
There are 2 accounts, so is there a way we could just ignore 1?

**Comment by fivetran-avinash** [comment]
Hi @kelsey-fecho , glad to hear that we've identified the potential root issue!

It's a good question about what to do here. When you examine the undeposited fund account data, is there any particular filter or condition that you think could be applied to these accounts that would exclude the one account you don't want? Is there some field or property to that one account that identifies it as something you wouldn't want to join in? 

Also, usually when we apply a fix to a transformations model, we want to make sure that this fix will work for all customers. If you can find a particular filter, do you think this fix would also work for other customers with multiple undeposited fund accounts? 

Or do you think the `quickbooks__undeposited_funds_reference` variable is the only path forward for filtering down that account? 

If you get a chance, please explore and let us know what you find! We'll also brainstorm on our end whether there are potential workaround solutions that we could use.

**Comment by fivetran-catfritz** [comment]
Hi @kelsey-fecho following up to @fivetran-avinash's comment above, we have confirmed that the issue is the lack of the mentioned variable in quickstart. In the meantime, we recommend using this package via dbt-core so you can take advantage of setting the `quickbooks__undeposited_funds_reference` var. If you have any additional comments or questions, you can continue to reach us via this thread!
