### ISSUE TITLE
Postgres Compatibility errors with v0.2.1

### ISSUE THREAD

**Issue by shubhamelucidate** [fivetran/dbt_quickbooks#13]
Tested Dbt run with latest version 0.2.1:

`dbt run  --vars '{using_address: false, using_bill: false, using_credit_memo: false, using_department: false, using_deposit: false, using_estimate: false, using_invoice: false, using_invoice_bundle: false, using_journal_entry: false, using_payment: false, using_refund_receipt: false, using_transfer: false, using_vendor_credit: false, using_sales_receipt: false}'`

Getting the following errors:

```
Completed with 2 errors and 0 warnings:

Database Error in model quickbooks__general_ledger (models/quickbooks__general_ledger.sql)
  function round(double precision, integer) does not exist
  LINE 134:         round(balance * multiplier, 2) as adjusted_balance
                    ^
  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
  compiled SQL at target/run/quickbooks/models/quickbooks__general_ledger.sql

Database Error in model quickbooks__expenses_sales_enhanced (models/quickbooks__expenses_sales_enhanced.sql)
  function round(double precision, integer) does not exist
  LINE 114:         round(balance * multiplier, 2) as adjusted_balance
                    ^
  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
  compiled SQL at target/run/quickbooks/models/quickbooks__expenses_sales_enhanced.sql

Done. PASS=14 WARN=0 ERROR=2 SKIP=3 TOTAL=19
```

Running on Postgres 11.10 (AWS RDS)

**Comment by shubhamelucidate** [comment]
PR here: https://github.com/fivetran/dbt_quickbooks/pull/14

**Comment by fivetran-joemarkiewicz** [comment]
Hi @shubhamelucidate thanks for opening this issue and calling out the rounding error for Postgres. Additionally, thank you for opening PR #14. Looking through the PR I decided to remove the rounding function as the Postgres rounding function is not compatibile with other databases and does not need to be included.

As such, I removed the round syntax from the two models you called out within your PR. I have since updated this within a new branch `pg-updates`. As this rounding error was not captured on our end when doing Postgres testing, I think it would be beneficial for you to install the latest working branch and run on your end to confirm there are no other Postgres syntax errors. You can install this branch by using the following config within your `packages.yml` file.

```yml
packages:
  - git: https://github.com/fivetran/dbt_quickbooks.git
    revision: pg-updates
    warn-unpinned: false
```

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as it has been incorporated within PR #15 and is now live within the v0.2.2 release of QuickBooks:

```yml
packages:
  - package: fivetran/quickbooks
    version: 0.2.2
```
