### ISSUE TITLE
FEATURE - [Adding customer_id to the general ledger]

### ISSUE THREAD

**Issue by joaolcorreia** [fivetran/dbt_quickbooks#18]
**Is your feature request related to a problem? Please describe.**
A common use data for accounting data is to build MRR rollforward tables (very important for subscription businesses), and cohort analysis, not to mention calculate customer LTV and other unit economics metrics.
In order perform these analysis you need a customer id, it would be great if the general_ledger had a customer_id when applicable.

**Describe the solution you'd like**
Adding customer_id to the general_ledger.

**Describe alternatives you've considered**
I considered joining tables to get this info but I think doing it in the package would be best.

**Please indicate the level of urgency and business impact of this request** 
No urgency, adding the customer level detail would make these models a lot more useful.

**Are you interested in contributing to this package?** 
I would prefer if someone who is already familiar with this package to do it, maybe it is not a big lift.

**Comment by fivetran-kristin** [comment]
Hey @joaolcorreia thanks for this request! We're currently evaluating and hoping to pick this work up next sprint.  We'll update this ticket with updates.

**Comment by fivetran-joemarkiewicz** [comment]
@joaolcorreia I am beginning work on this feature request and had a quick question for you. I have been able to locate the `customer_id` fields within the majority of the double entry base tables which we could then bring into the General Ledger final model.

My question for you is if the structure of the `quickbooks__general_ledger` as it currently is works for adding the customer_id's? For example if we are able to find a customer_id associated with a payment, would you find it useful to have the customer_id associated with all debits and credits related to that payment? Or would it be more beneficial to create a separate transactions model which doesn't break out transactions for debit and credit reporting purposes? 

Obviously the first option would be the easiest, but I am unsure if that would provide an accurate view of what you are looking for since an aggregation on the customer_id in that scenario would most likely zero out since the debits and credits are offsetting. Let me know, because if we decide that the second option makes the most sense then we will most likely need to scope more work out for this Issue and include it in its own release.

Thanks!

**Comment by joaolcorreia** [comment]
hi @fivetran-joemarkiewicz, yes just adding the customer_id to the general ledger works (when exists is populated) otherwise it is null. Since you are at it you can also add the vendor_id to the general ledger, this would make this table multi-function and very valuable.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @joaolcorreia 👋 

I have been able to open the draft PR #22 which adds the `customer_id` and `vendor_id` to the `quickbooks__general_ledger` model. Prior to opening the draft PR for review, I would appreciate your input on the updates made. As mentioned, since the behavior of the GL model is to create offsetting entries you will notice that each transaction will have the customer or vendor id recorded for both the debit and credit entry when present. Would you be able to confirm this is the approach you were expecting? Feel free to install the branch the draft PR is built from to test out the results:

```yml
packages:
  - git: https://github.com/fivetran/dbt_quickbooks.git
    revision: customer-id-add
    warn-unpinned: false
```

Let me know if the changes are what you expected, and I can convert the draft PR to be ready for review from there. Thanks!

**Comment by joaolcorreia** [comment]
Hi @fivetran-joemarkiewicz, this is great! 
With a simple query I can build revenue by customer from the GL with a simple join!.
Thank you for making this, getting an MRR table is now much simpler!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much for your input @joaolcorreia! After your feedback I have been able to merge the PR and publish the `v0.2.4` release of the quickbooks package. This latest version of the package should be live on the dbt hub by the end of the day.

Thank you again and please let us know if you run into any other questions or issues.
