### ISSUE TITLE
FEATURE - Cashflow Statement

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_quickbooks#31]
**Are you a Fivetran customer?** 
yes, Christoph, Sustain.life

**Is your feature request related to a problem? Please describe.**
No visibility into cashflow situation based on current models

**Describe the solution you'd like**
We would like to see a cashflow report similar to the balance sheet etc.

**Describe alternatives you've considered**
using the report available in the Quickbooks UI

**Additional context**

**Please indicate the level of urgency and business impact of this request** 

**Provide us context so that we can prioritize accordingly. -->

**Are you interested in contributing to this package?** 
Yes, happy to help 

implement this feature? -->
- [ ] Yes, I can do this and open a PR for your review.
- [ x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Hey @leinemann thanks so much for opening this Feature Request!

We have actually received a few other requests from users of this package to build out a cash flow statement as a final model. This will be a report we would like to integrate into the package in the near future. I imagine this will be a feature our team will work to integrate next quarter. It would be great to keep the conversation here once we start working on this feature as well!

I will have to re-jog my memory of all those cash flow statements I had to do in my accounting classes years ago. Because of that, it would be great to collaborate with you to validate the model once we have developed it! 😃

**Comment by leinemann** [comment]
that is great, thanks @fivetran-joemarkiewicz! Yes, although far from being a finance expert, I can help to validate as I can compare against the reports that quickbooks offer where I can see things like balance sheet and PnL tying up already.

**Comment by fivetran-avinash** [comment]
Hi @leinemann ! [We've added the cash flow statement in the 0.7.0 release of our package](https://github.com/fivetran/dbt_quickbooks_source/releases/tag/v0.7.0). Can you update your `packages.yml`, test it out and let us know your thoughts and feedback?

We've also added some interesting configurability to customize your cash flow types and ordering! [Read more about it in our Fivetran Community post.](https://community.fivetran.com/t5/user-group-for-dbt/configure-your-quickbooks-cash-flow-statement-using-seed-files/td-p/559)

Since this is resolved, we're going to close this issue, but please respond here if you have any thoughts or questions. Cheers!
